boostcamp-2020/Project17-B-Map

BoostClusteringMaB/BoostClusteringMaB/ViewController.swift
- 변수 이름, 괄호 추가 등 수정
=> [feature/touch for creating marker] Merge conflict 문제

BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj, BoostClusteringMaB/BoostClusteringMaB/CoreData/CoreDataContainer.swift, BoostClusteringMaB/BoostClusteringMaB/CoreData/CoreDataLayer.swift, BoostClusteringMaB/BoostClusteringMaB/CoredataLayer.swift, BoostClusteringMaB/BoostClusteringMaBTests/CoreDataTests.swift
- 코어데이터에서 특정 poi만 제거하는 remove 함수 추가
- 코어데이터에서 전체 poi를 제거하는 removeAll 함수 추가
- remove / removeAll 테스트 코드 추가
=> [feature/coredata_remove] remove / removeAll 함수 추가

BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj, BoostClusteringMaB/BoostClusteringMaB.xcodeproj/xcshareddata/xcschemes/BoostClusteringMaB.xcscheme, BoostClusteringMaB/BoostClusteringMaB/KMeans/Cluster.swift, BoostClusteringMaB/BoostClusteringMaB/KMeans/KMeans.swift, BoostClusteringMaB/BoostClusteringMaB/KMeans/LinkedList.swift, BoostClusteringMaB/BoostClusteringMaBTests/KMeansTest.swift, BoostClusteringMaB/BoostClusteringMaBTests/LinkedListTests.swift
> 링크드리스트는 자료구조에서 오류가 없어야 하므로 테스트 커버리지 98.9%로 작성했습니다.
- 테스트를 하면서 테스트가 실패한 부분을 수정했습니다.
> 아직 어떻게 해야할지 고민입니다.
=> [Feature/linked list test] LinkedList테스트코드 작성

BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj, BoostClusteringMaB/BoostClusteringMaB/ViewController.swift, BoostClusteringMaB/BoostClusteringMaB/extension/NMFMarker+Animation.swift
- moveWithAnimation(_ mapView:, to destination:, complete: ) 를 이용해 마커 간 이동 애니메이션
- 마커의 position을 이동시켜 애니메이션 구현
- div 값을 통해 속도가 조절됨
- NMFMarker 애니메이션을 통한 클러스터링 병합과 분할 애니메이션 구현
- 이전 클러스터들과의 거리를 비교해, 합쳐지거나 분할될 클러스터 선택
- 병합 애니메이션   
- <img src=https://user-images.githubusercontent.com/45285737/100075836-ce336400-2e83-11eb-9d30-991f99b52586.gif width=60%/>    
- 분할 애니메이션   
- <img src=https://user-images.githubusercontent.com/45285737/100075843-d095be00-2e83-11eb-93c6-83d01a4436b8.gif width=60%/>
- 추후 성능 개선 필요
=> [feature/marker animation] 마커 애니메이션

BoostClusteringMaB/BoostClusteringMaB/KMeans/Clustering/ConvexHull.swift
- ConvexHull 반시계방향 정렬 시 기준점을 빼고 정렬하도록 변경했습니다.
=> fix : convexHull 가끔 선을 안그리던 버그 수정

BoostClusteringMaB/BoostClusteringMaB/Loading/LoadViewController.swift, BoostClusteringMaB/BoostClusteringMaB/MarkerAnimateController.swift, BoostClusteringMaB/BoostClusteringMaB/Persistence/CoreData/CoreDataLayer.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainViewController.swift, BoostClusteringMaB/BoostClusteringMaBTests/Mocks/CoreDataLayerMock.swift
- 출발과 도착점이 같을 시, 해당 마커의 애니메이션은 실행하지 않음
=> [feature/fix animation] 애니메이션 수정

BoostClusteringMaB/BoostClusteringMaB/Clustering/Cluster.swift, BoostClusteringMaB/BoostClusteringMaB/Clustering/Clustering.swift, BoostClusteringMaB/BoostClusteringMaB/Clustering/ConvexHull.swift, BoostClusteringMaB/BoostClusteringMaB/Clustering/KMeans.swift, BoostClusteringMaB/BoostClusteringMaB/CoreData/CoreDataLayer.swift, BoostClusteringMaB/BoostClusteringMaB/CoreData/Models/ManagedPOI+CoreDataClass.swift, BoostClusteringMaB/BoostClusteringMaB/Extension/CGPoint+Distance.swift, BoostClusteringMaB/BoostClusteringMaB/Extension/NMFMarker+.swift, BoostClusteringMaB/BoostClusteringMaB/Extension/String+Bundle.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/View/DetailCollectionViewCell.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainInteractor.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainPresenter.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift, BoostClusteringMaB/BoostClusteringMaB/Util/JsonParser.swift
- Cell클릭 시 해당 위치로 줌인 되면서 확대기능
- Cluster클릭 시 해당 클러스터 줌인 되면서 CollectionView Data Reload
=> [Feature/cluster click reload] Cell 클릭 시 확대, Cluster 클릭 시 cell 데이터 update

BoostClusteringMaB/BoostClusteringMaB/Models/LatLng.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainPresenter.swift
- 클러스터가 무게중심으로 그려지다보니 ConvexHull로 그려진 영역에 이상한 위치에 클러스터가 그려졌음 
- LatLngs 값들의 무게중심에서 ConvexHull의 Center로 수정
=> [Feature/cluster center] 클러스터 그려지는 위치 센터로 수정

BoostClusteringMaB/BoostClusteringMaB.xcodeproj/xcshareddata/xcschemes/BoostClusteringMaB.xcscheme, BoostClusteringMaB/BoostClusteringMaB/Clustering/Clustering.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainPresenter.swift
1. Time Out Error
- Thread Sanitizer 해제 (쓰레드 하나하나 검사하느라 시간이 오래걸려서 Time Out이 나서 제거 후 해결)
=> [Hotfix/time out error] 처음 로딩에서 TimeOut이 나던 Error 해결

BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj, BoostClusteringMaB/BoostClusteringMaB/Clustering/Clustering.swift, BoostClusteringMaB/BoostClusteringMaB/Clustering/KMeans.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainPresenter.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
- KMeans.run()를 하고 난 뒤 MeanDBI를 구하는 순으로 동작해야 하는데 run하는 도중에 MeanDBI를 구해서 0으로 나오는 결과
- queue.cancelAllOperations()를 해도 queue에서 바로 사라지지 않는 문제
- KMeans를 배열에 넣어두고 addBarrierBlock에서 DBI의 min값을 구하는 과정으로 수정
- 아래 메소드를 KMeans안에 넣어두고 run안에서 돌리는 함수들을 runOperation으로 묶어줌
```swift
func runOperation(_ operations: [() -> Void]) {
guard !isCancelled else { return }
operations.forEach({
$0()
})
}
```
=> [Hotfix/operation queue] OperationQueue 수정

BoostClusteringMaB/BoostClusteringMaB/Extension/NMFMarker+.swift, BoostClusteringMaB/BoostClusteringMaB/MarkerAnimateController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainPresenter.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Detail.storyboard, BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/MarkerImageView.swift
- 가장 큰 클러스터의 크기 비율에 맞춰 나머지 클러스터의 크기 조정
- old/new 마커의 radius 값을 추가로 받아 해당 크기에 맞게 애니메이션
=> [feature/adjust marker image view] 클러스터 마커 동적 이미지 크기 / 애니메이션

BoostClusteringMaB/BoostClusteringMaB/Clustering/Clustering.swift
- 세계지도에서 k범위 역전되던 현상 수정
- 4번의 터치로 갈 수 있게 사람들이 자주 쓰는 줌 레벨에서 최소 k갯수를 늘림
=> [feat : k_range] k 범위 조정

BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj, BoostClusteringMaB/BoostClusteringMaB/Clustering/ClusteringProtocol.swift, BoostClusteringMaB/BoostClusteringMaB/Extension/NMFMarker+.swift, BoostClusteringMaB/BoostClusteringMaB/Extension/UIColor+.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainPresenter.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/MarkerImageView.swift, BoostClusteringMaB/BoostClusteringMaBTests/KMeans/ClusteringTests.swift
- 터치된 마커 색 전환
- 첫 번째 터치 시 캡션을 통해 좌표 정보 표시
- 기존 captionText로 사용하던 기능은 userInfo로 이동
- 두 번째 터치 시, 삭제 alert 표시
=> [Feature/improving marker] 마커 터치

BoostClusteringMaB/BoostClusteringMaB/CoreData/CoreDataLayer.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Detail.storyboard
- DetailViewController에서 불필요한 코드 삭제
- DiffableDataSource를 사용해서 구현
- 검색 NSPredicate를 추가 시켜 검색기능 추가
=> [Feature/detail view search] CollectionView수정, 검색기능 추가

BoostClusteringMaB/BoostClusteringMaB/Clustering/Cluster.swift, BoostClusteringMaB/BoostClusteringMaB/Clustering/Clustering.swift, BoostClusteringMaB/BoostClusteringMaB/Clustering/KMeans.swift, BoostClusteringMaB/BoostClusteringMaB/Models/LatLng.swift, BoostClusteringMaB/BoostClusteringMaB/Models/LinkedList.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/Loading/LoadViewController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
- 클러스터의 Center 연산 중복 제거
- 미리 모든 점들의 합을 계산해 놓고 활용
- Cluster의 DBI값 연산 중복 제거
- 미리 DBI들을 DP처럼 Deviations에 저장해 놓고 활용
=> [Hotfix/cluster optimization] 클러스터링 개선사항

BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Detail.storyboard
- 화면 움직일 때 검색창을 빈칸으로 바뀌게 수정
- cancel눌렀을 때 검색 Text 삭제
- x눌렀을 때 검색 Text 삭제
=> [Hotfix/search text remove] 검색 기능 개선

BoostClusteringMaB/BoostClusteringMaB/Extension/NMFMarker+.swift, BoostClusteringMaB/BoostClusteringMaB/MainAnimationController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/MarkerImageView.swift, BoostClusteringMaB/BoostClusteringMaBTests/Mocks/CoreDataLayerMock.swift
- label font size 현재 text.count와 size에 맞춰 동적으로 조정
- 애니메이션을 맵 컨트롤러 뒤에서 실행
- 해당하는 iconImage를 사용해 애니메이션하는 방식으로 변경
=> [feature/improving_marker] 마커 이미지 뷰 / 애니메이션

BoostClusteringMaB/BoostClusteringMaB/MainAnimationController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift, BoostClusteringMaB/BoostClusteringMaBTests/Mocks/CoreDataLayerMock.swift
- 처음에는  빨간 점으로 깜빡이는 애니메이션으로 구현했는데 사용자에게 눈에 띄지 않음
- pulse 애니메이션으로 수정
=> [Feature/improving dot animation] Dot Animation 변경

BoostClusteringMaB/BoostClusteringMaB/MainAnimationController.swift
- 같은 점 마커 이미지는 애니메이션 하지 않는 뷰를 애니메이션 때 삽입
=> [Fix] 애니메이션 시, 마커 사라짐

BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
=> [Hotfix/cancel_button] cancelButtonTouched에 reloadPOI추가

BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj, BoostClusteringMaB/BoostClusteringMaB/Extension/NMFCameraUpdate+.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainInteractor.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
- add할 때 Zoom In 하는데 도중에 클러스터링이 돼서 화면에 이상하게 나옴
- remove하고 난 뒤 클러스터링을 진행이 어색하다고 판단 
- Zoom In이 되고나서 POI를 add하게 수정
- remove할 때는 클러스터링 기능 삭제
=> [Hotfix/animation add remove bug] POI add, remove할 때 animation버그 수정

BoostClusteringMaB/BoostClusteringMaB/MainAnimationController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/MarkerImageView.swift
- 그림자 적용
- View -> Layer로 변경
- 수직 정렬 된 TextLayer인 MarkerTextLayer 추가
- 리프마커에 병합/리프마커가 분열을 안하도록 변경
- 고정된 위치는 반투명 애니메이션
=> [feature/improving marker] 마커 이미지 / 애니메이션 개선

BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/DrawerMenu/DrawerController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Base.lproj/Main.storyboard
- Drawer가 나올 시 BottomSheet의 Switch button이 위에있는 현상
- viewDidAppear에서 bringSubviewToFront를 사용해서 순서 재정의
- Drawer swipe와 overlay 터치 할 시 사라지게 만들기
=> [Hotfix/view_order] view 순서 재정의

BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
- Cluster터치시 서치바 뒤에 가려진 부분은 패치하지 않게 변경
- 키보드 이슈 해결
-  검색 후 스크롤 시 키보드 숨기기
-  검색 버튼 누르면 키보드 숨기기
=> [Fix/mapview fetch bounds] Cluster 터치시 fetch 범위 오류 수정

BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Detail.storyboard
- BottomSheet이 중간높이 일 때 Cell이 스크롤이 되지 않음
- 상태에 따라 높이 조절
=> [Hotfix/collection view scroll] BottomSheet 상태에 따라 frame조절

BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/DrawerMenu/DrawerController.swift
- VisualEffect 어색한거 수정
- Cell클릭시 키보드 내리기
- 검색할 때 뷰 full size로 변경하기
=> [Hotfix/chore] 자잘한 오류 수정

BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
- 슬라이딩 애니메이션이 끝난 뒤, 스위치 버튼 표시
=> [Feature/fix intermittent animation error]

BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift, BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
- 회전 시, 화면 좌표내 데이터를 제대로 받아오지 못하는 문제
- 회전을 지원하는 기능이 추가 되기 전까지, 회전 기능 disable
- 카메라 이동 중엔 셀 터치 무효화
=> [Hotfix/touch and animation] 터치, 애니메이션 오류
